### ISSUE TITLE
Riker's g++ wrapper should fail when no system g++ is installed

### ISSUE THREAD

**Issue by dbarowy** [curtsinger-lab/riker#44]
Currently, it "fails" with a successful error code, which is misleading when trying to understand why cram tests succeed when they shouldn't.

**Comment by ccurtsinger** [comment]
It turns out the wrapper does fail with the right error code. It's Riker that happily exits with code 0 so cram doesn't complain. Rikerfile itself also exits with code 0 in all our tests, and it seems weird to force exit code handling into the simple build spec. I'm not even sure we should assign special meaning to process exit codes given that non-standard exit codes pop up from time to time.

For now I'll just update the wrapper to print an error message and leave the rest untouched.
