### ISSUE TITLE
Thoughts on indicating parallelism in Rikerfile

### ISSUE THREAD

**Issue by drudru** [curtsinger-lab/riker#50]
I have just read the paper on Riker.
I have not yet used Riker.

I was wondering what the thoughts are on indicating that something should be done in parallel.

I realize this is probably more of a shell problem than a Riker problem

It would seem, though that, including a binary that executed its arguments in parallel would be helpful to Riker. It could act as a sentinnel to indicate that arguments are OK to run in parallel.

**Comment by ccurtsinger** [comment]
You're right, this is a bit of a shell expression problem. You can always run arguments in the background with `&` and then use `wait` to join them. Riker also includes a compiler wrapper that takes multi-source compiler invocations for C and C++ and kicks off the separate compilation steps in parallel instead of serial. The wraper is really a "fix" for the fact that `clang` and `gcc` don't provide a flag to run compilation steps in parallel.

The downside with any sort of Riker-specific way of indicating parallelism is that the Rikerfile is then no longer runnable as a standalone script. We see that as a big advantage, since it allows someone without Riker installed to easily run the build as a one-off. It also gives us a good baseline to compare to so we can confirm that Riker's incremental build really is equivalent to what you'd get by running the full build without Riker.

There may be a more clever way for someone to invoke things in parallel, but I'm not enough of a shell wizard to know about it.
