### ISSUE TITLE
riker not compatible with cmake

### ISSUE THREAD

**Issue by menogrey** [curtsinger-lab/riker#56]
the cmake program will check C and CXX compiler with command `/usr/share/rkr/wrappers/cc CMakeCCompilerId.c` , and the riker wrapper cc will be in a dead loop because of creating new process `/usr/share/rkr/wrappers/cc CMakeCCompilerId.c`  repeatedly. I think this is a bug, because using `cc_path=$(realpath cc) && $cc_path xxx.c` is very normal.

I try to debug that and found the wrapper's argv[0] is `/usr/share/rkr/wrappers/cc`.

My cmake version is 3.16 and i think newer version also has this issue.

```
(ir) traced [Command cmake ..]: ExpectResult(r454, SUCCESS) [build]
(exec) New command [Command cc CMakeCCompilerId.c] did not match any previous command.
(ir) traced [Command cmake ..]: Launch([Command cc CMakeCCompilerId.c], [r3=r3, r4=r443, r5=r454, r6=r6, r7=r447, r8=r447])
(exec) [Command cmake ..] is launching [Command cc CMakeCCompilerId.c] as a traced command
```

```
(trace) [Thread 9002 in [Process 9002 (cc CMakeCCompilerId.c)]]: injecting signal SIGTRAP (status=32773)
(trace) [Thread 9001 in [Process 9001 (cc CMakeCCompilerId.c)]]: stopped on syscall wait4
(trace) [Thread 9001 in [Process 9001 (cc CMakeCCompilerId.c)]]: wait4(-1, 0x7ffc7f21b1c8, 0)
(ir) traced [Command cc CMakeCCompilerId.c]: r633 = PathRef(r3, "usr/share/rkr/wrappers/cc", r--)
(ir) traced [Command cc CMakeCCompilerId.c]: ExpectResult(r633, SUCCESS) [build]
(ir) traced [Command cc CMakeCCompilerId.c]: MatchContent(r633, [file content: mtime=1698077306.720565907 cached=false]) [build]
```

**Comment by ccurtsinger** [comment]
Okay, I can reproduce this bug now. Riker's compiler wrapper is being invoked with a complete path, and it just invokes itself again instead of the appropriate `cc` on the system. I've got a workaround in progress, but there are other issues with the wrapper's handling of some flags that CMake passes to `cc`.

In the meantime, you can run Riker without the compiler wrapper by passing the `--no-wrapper` flag.

As a point of interest, can you explain why you are running CMake under Riker? I can come up with some plausible use cases for wrapping an existing build system, but I want to be sure I'm not missing an important one.
